### ISSUE TITLE
GLException$InvalidOperation in different tests

### ISSUE THREAD

**Issue by DamianX** [sriharshachilakapati/SilenceEngine#3]
See the logs below.
These are the outputs from running, respectively, Geom3DTest and Graphics2DTest.
I've just recently started digging into the engine (great job, btw!), but from my limited understanding it appears the ResourceLoader is trying to draw the logo before OpenGL has been initialized.

```
[INFO 03/15/2015 9:18:41 PM] Initializing SilenceEngine. Platform identified as WINDOWS_64
[INFO 03/15/2015 9:18:41 PM] Initializing LWJGL library. Extracting natives
[INFO 03/15/2015 9:18:41 PM] LWJGL version 3.0.0a is initialised
[INFO 03/15/2015 9:18:42 PM] Initializing Audio Engine with OpenAL 1.1
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
[INFO 03/15/2015 9:18:42 PM] Audio Engine initialized successfully, with device OpenAL Soft
[INFO 03/15/2015 9:18:42 PM] SilenceEngine version 0.0.3a was initialized successfully
[INFO 03/15/2015 9:18:42 PM] Initializing the Game resources
com.shc.silenceengine.graphics.opengl.GLException$InvalidOperation: The specified operation is not allowed in current state
	at com.shc.silenceengine.graphics.opengl.GLError.check(GLError.java:79)
	at com.shc.silenceengine.graphics.opengl.GLError.check(GLError.java:54)
	at com.shc.silenceengine.graphics.opengl.Program.setUniform(Program.java:158)
	at com.shc.silenceengine.graphics.opengl.Program.setUniform(Program.java:163)
	at com.shc.silenceengine.graphics.programs.DefaultProgram.prepareFrame(DefaultProgram.java:84)
	at com.shc.silenceengine.graphics.Batcher.flush(Batcher.java:219)
	at com.shc.silenceengine.graphics.Batcher.end(Batcher.java:185)
	at com.shc.silenceengine.graphics.Graphics2D.drawTexture(Graphics2D.java:306)
	at com.shc.silenceengine.graphics.Graphics2D.drawTexture(Graphics2D.java:267)
	at com.shc.silenceengine.graphics.Graphics2D.drawTexture(Graphics2D.java:313)
	at com.shc.silenceengine.core.ResourceLoader.renderProgress(ResourceLoader.java:226)
	at com.shc.silenceengine.core.ResourceLoader.startLoading(ResourceLoader.java:167)
	at com.shc.silenceengine.tests.Geom3DTest.init(Geom3DTest.java:71)
	at com.shc.silenceengine.core.Game.start(Game.java:188)
	at com.shc.silenceengine.tests.Geom3DTest.main(Geom3DTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
AL lib: (EE) alc_cleanup: 1 device not closed
```

```
[INFO 03/15/2015 9:31:20 PM] Initializing SilenceEngine. Platform identified as WINDOWS_64
[INFO 03/15/2015 9:31:20 PM] Initializing LWJGL library. Extracting natives
[INFO 03/15/2015 9:31:20 PM] LWJGL version 3.0.0a is initialised
[INFO 03/15/2015 9:31:20 PM] Initializing Audio Engine with OpenAL 1.1
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
[INFO 03/15/2015 9:31:20 PM] Audio Engine initialized successfully, with device OpenAL Soft
[INFO 03/15/2015 9:31:20 PM] SilenceEngine version 0.0.3a was initialized successfully
[INFO 03/15/2015 9:31:20 PM] Initializing the Game resources
com.shc.silenceengine.graphics.opengl.GLException$InvalidOperation: The specified operation is not allowed in current state
	at com.shc.silenceengine.graphics.opengl.GLError.check(GLError.java:79)
	at com.shc.silenceengine.graphics.opengl.GLError.check(GLError.java:54)
	at com.shc.silenceengine.graphics.opengl.Program.setUniform(Program.java:158)
	at com.shc.silenceengine.graphics.opengl.Program.setUniform(Program.java:163)
	at com.shc.silenceengine.graphics.programs.DefaultProgram.prepareFrame(DefaultProgram.java:84)
	at com.shc.silenceengine.graphics.Batcher.flush(Batcher.java:219)
	at com.shc.silenceengine.graphics.Batcher.end(Batcher.java:185)
	at com.shc.silenceengine.graphics.Graphics2D.drawTexture(Graphics2D.java:306)
	at com.shc.silenceengine.graphics.Graphics2D.drawTexture(Graphics2D.java:267)
	at com.shc.silenceengine.graphics.Graphics2D.drawTexture(Graphics2D.java:313)
	at com.shc.silenceengine.core.ResourceLoader.renderProgress(ResourceLoader.java:226)
	at com.shc.silenceengine.core.ResourceLoader.startLoading(ResourceLoader.java:143)
	at com.shc.silenceengine.tests.Graphics2DTest.init(Graphics2DTest.java:59)
	at com.shc.silenceengine.core.Game.start(Game.java:188)
	at com.shc.silenceengine.tests.Graphics2DTest.main(Graphics2DTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by sriharshachilakapati** [comment]
@DamianX 

I think I found the issue, which is not the problem of `ResourceLoader` but is the new `Display` class implementation, this occurs right after calling `Display.setResizable(false)` method. Thanks for reporting, I'll investigate into this issue further.

**Comment by sriharshachilakapati** [comment]
@DamianX 

I have solved the issue, it turned up that I forgot to update the Display after replacing the window handle. If you also confirm that this is gone I'll close this issue.

**Comment by DamianX** [comment]
Yep, it works. Case closed I guess.

**Comment by sriharshachilakapati** [comment]
Good to hear, I'm now closing this issue.
