### ISSUE TITLE
FilePath.calculateResourceSize() is crashing when called from IDE

### ISSUE THREAD

**Issue by sriharshachilakapati** [sriharshachilakapati/SilenceEngine#53]
The exception being thrown is

```
com.shc.silenceengine.core.SilenceException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.shc.silenceengine.io.FilePath.calculateResourceSize(FilePath.java:645)
	at com.shc.silenceengine.io.FilePath.sizeInBytes(FilePath.java:599)
	at com.shc.silenceengine.io.FilePath.toString(FilePath.java:762)
	at net.epoxide.client.ResourceManager.init(ResourceManager.java:24)
	at net.epoxide.EpoxideGame.init(EpoxideGame.java:38)
	at com.shc.silenceengine.core.Game.start(Game.java:268)
	at net.epoxide.EpoxideGame.main(EpoxideGame.java:18)

	at com.shc.silenceengine.core.SilenceException.reThrow(SilenceException.java:73)
	at com.shc.silenceengine.core.SilenceEngine.lambda$static$66(SilenceEngine.java:178)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1952)
```

Originally posted on the forum at http://silenceengine.goharsha.com/forum/newbie-questions/crashing-when-tostring/

**Comment by sriharshachilakapati** [comment]
This issue is being addressed with a more simple way by finding the correct JAR file by parsing the URL of the resource, and not guessing it via the code source in the protection domain. Also I'm splitting up the `FilePath` class into `ResourceFilePath` and `ExternalFilePath` classes. The `FilePath` class is made abstract, but the same API is available previously.
