### ISSUE TITLE
ALDevice.destroy() does not exist in latest LWJGL 3 release nightlies

### ISSUE THREAD

**Issue by ShadowChild** [sriharshachilakapati/SilenceEngine#54]
In the latest LWJGL 3 release nightlies ALDevice.destroy() has been changed to ALDevice.close().

I'm using LWJGL 3.0.0 build 4

Due to this change the game crashes on exit.

Heres the log:

```
[TRACE 12/03/2015 5:57:11 PM]
com.shc.silenceengine.core.SilenceException: java.lang.NoSuchMethodError: org.lwjgl.openal.ALDevice.destroy()V
	at com.shc.silenceengine.audio.openal.ALContext.dispose(ALContext.java:95)
	at com.shc.silenceengine.audio.AudioEngine.dispose(AudioEngine.java:79)
	at com.shc.silenceengine.core.SilenceEngine.dispose(SilenceEngine.java:150)
	at com.shc.silenceengine.core.gameloops.FixedCatchingUpGameLoop.stop(FixedCatchingUpGameLoop.java:217)
	at com.shc.silenceengine.core.gameloops.FixedCatchingUpGameLoop.start(FixedCatchingUpGameLoop.java:110)
	at com.shc.silenceengine.core.Game.start(Game.java:267)
	at com.shc.silenceengine.core.Game.start(Game.java:217)
	at io.github.shadowchild.vdgame.Main.main(Main.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

	at com.shc.silenceengine.core.SilenceException.reThrow(SilenceException.java:73)
	at com.shc.silenceengine.core.SilenceEngine.lambda$static$67(SilenceEngine.java:178)
	at com.shc.silenceengine.core.SilenceEngine$$Lambda$5/1789447862.uncaughtException(Unknown Source)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1952)

AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by sriharshachilakapati** [comment]
I haven't still updated the dependency LWJGL version, it's still at nightly 1. Will update right now.

**Comment by sriharshachilakapati** [comment]
Fixed, you can now pull the latest changes and it should work fine. Thank you for reporting the issue here.

**Comment by ShadowChild** [comment]
No problem, loving the engine so far.
