### ISSUE TITLE
SilenceException related to sound on macosx

### ISSUE THREAD

**Issue by fagossa** [sriharshachilakapati/SilenceEngine#58]
Hi Sri,

I am using your engine for the first time. So, basically I took the source from [one of your applications](https://github.com/sriharshachilakapati/AutoInvaders) and tried to compile and runnit. Everything compiles but at runtime i'm getting several errors.

The following log shows the configuration used to run the example:

```
[INFO 12/29/2015 9:44:14 PM] Initializing LWJGL library. Extracting natives.
[INFO 12/29/2015 9:44:14 PM] LWJGL version 3.0.0 build 7 is initialised
[INFO 12/29/2015 9:44:14 PM] [LWJGL] Version: 3.0.0 build 7
[INFO 12/29/2015 9:44:14 PM] [LWJGL] 	 OS: Mac OS X v10.11
[INFO 12/29/2015 9:44:14 PM] [LWJGL] 	JRE: 1.8.0_25 x86_64
[INFO 12/29/2015 9:44:14 PM] [LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.25-b02 by Oracle Corporation
[INFO 12/29/2015 9:44:14 PM] [LWJGL] Loaded library from org.lwjgl.librarypath: lwjgl
[INFO 12/29/2015 9:44:14 PM] [LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[INFO 12/29/2015 9:44:14 PM] [LWJGL] Loaded native library: /var/folders/5h/f2t3rrvs1mg1cjtsylppphc00000gn/T/SilenceEngine5669742121614165815/libjemalloc.dylib
[INFO 12/29/2015 9:44:14 PM] [LWJGL] MemoryUtil allocator: JEmallocAllocator
[INFO 12/29/2015 9:44:14 PM] [LWJGL] Loaded native library: /var/folders/5h/f2t3rrvs1mg1cjtsylppphc00000gn/T/SilenceEngine5669742121614165815/libglfw.dylib
[INFO 12/29/2015 9:44:14 PM] Initializing SilenceEngine. Platform identified as MACOSX
[INFO 12/29/2015 9:44:14 PM] Running AWT fix on Mac OS X, needed for LWJGL to run
[INFO 12/29/2015 9:44:14 PM] [LWJGL] Loaded native library: libobjc.dylib
[INFO 12/29/2015 9:44:15 PM] [LWJGL] Loaded native library bundle: /System/Library/Frameworks/OpenGL.framework
```
Until this point it all seems good, however:

```
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniform1dEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniform2dEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniform3dEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniform4dEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniform1dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniform2dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniform3dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniform4dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix2dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix3dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix4dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix2x3dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix2x4dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix3x2dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix3x4dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix4x2dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix4x3dvEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glVertexArrayVertexAttribDivisorEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glTextureStorage1DEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glTextureStorage2DEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glTextureStorage3DEXT
[WARNING 12/29/2015 9:44:15 PM] [LWJGL] Failed to locate address for GL function glVertexArrayVertexAttribLOffsetEXT
[INFO 12/29/2015 9:44:15 PM] Clearing out OpenGL errors
2015-12-29 21:44:15.319 java[21253:619138] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
```

And finally an exception related to audio

```
com.shc.silenceengine.core.SilenceException: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.shc.silenceengine.audio.ISoundReader.create(ISoundReader.java:119)
	at com.shc.silenceengine.audio.Sound.<init>(Sound.java:74)
	at com.shc.silenceengine.audio.AudioEngine.getSound(AudioEngine.java:105)
	at com.shc.silenceengine.core.ResourceLoader.soundLoadHelper(ResourceLoader.java:107)
	at com.shc.silenceengine.core.ResourceLoader$$Lambda$65/523691575.load(Unknown Source)
	at com.shc.silenceengine.core.ResourceLoader.asyncLoadResources(ResourceLoader.java:284)
	at com.shc.silenceengine.core.ResourceLoader$$Lambda$70/990398217.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
````

Do you have any idea of how to solve this problem?

thanks a lot!

**Comment by sriharshachilakapati** [comment]
Is that exception all? I think it is incomplete, there should be a `Caused by:` line which is explaining about the real issue. It would also help if you tell me whether the sound file you are loading is a WAV or a OGG file.

**Comment by sriharshachilakapati** [comment]
@fagossa Any updates?

**Comment by fagossa** [comment]
Hi,
I upgraded my jdk to jdk_8_066

```
[INFO 01/03/2016 12:11:34 PM] LWJGL version 3.0.0 build 7 is initialised
[INFO 01/03/2016 12:11:34 PM] [LWJGL] Version: 3.0.0 build 7
[INFO 01/03/2016 12:11:34 PM] [LWJGL] 	 OS: Mac OS X v10.11
[INFO 01/03/2016 12:11:34 PM] [LWJGL] 	JRE: 1.8.0_66 x86_64
[INFO 01/03/2016 12:11:34 PM] [LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.66-b17 by Oracle Corporation
```

Here is the full trace:

```
[INFO 01/03/2016 12:11:34 PM] [LWJGL] Loaded library from org.lwjgl.librarypath: lwjgl
[INFO 01/03/2016 12:11:34 PM] [LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[INFO 01/03/2016 12:11:34 PM] [LWJGL] Loaded native library: /var/folders/5h/f2t3rrvs1mg1cjtsylppphc00000gn/T/SilenceEngine6877229952434969225/libjemalloc.dylib
[INFO 01/03/2016 12:11:34 PM] [LWJGL] MemoryUtil allocator: JEmallocAllocator
[INFO 01/03/2016 12:11:34 PM] [LWJGL] Loaded native library: /var/folders/5h/f2t3rrvs1mg1cjtsylppphc00000gn/T/SilenceEngine6877229952434969225/libglfw.dylib
[INFO 01/03/2016 12:11:34 PM] Initializing SilenceEngine. Platform identified as MACOSX
[INFO 01/03/2016 12:11:34 PM] Running AWT fix on Mac OS X, needed for LWJGL to run
[INFO 01/03/2016 12:11:34 PM] [LWJGL] Loaded native library: libobjc.dylib
[INFO 01/03/2016 12:11:34 PM] [LWJGL] Loaded native library bundle: /System/Library/Frameworks/OpenGL.framework
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniform1dEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniform2dEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniform3dEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniform4dEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniform1dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniform2dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniform3dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniform4dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix2dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix3dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix4dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix2x3dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix2x4dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix3x2dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix3x4dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix4x2dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix4x3dvEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glVertexArrayVertexAttribDivisorEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glTextureStorage1DEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glTextureStorage2DEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glTextureStorage3DEXT
[WARNING 01/03/2016 12:11:34 PM] [LWJGL] Failed to locate address for GL function glVertexArrayVertexAttribLOffsetEXT
[INFO 01/03/2016 12:11:34 PM] Clearing out OpenGL errors
2016-01-03 12:11:34.742 java[23273:682453] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
[INFO 01/03/2016 12:11:36 PM] Initializing Audio Engine with OpenAL 1.1
[INFO 01/03/2016 12:11:36 PM] [LWJGL] Loaded native library: /var/folders/5h/f2t3rrvs1mg1cjtsylppphc00000gn/T/SilenceEngine6877229952434969225/libopenal.dylib
[INFO 01/03/2016 12:11:36 PM] Audio Engine initialized successfully, with device OpenAL Soft
[INFO 01/03/2016 12:11:36 PM] SilenceEngine version 0.4.1b was initialized successfully
[INFO 01/03/2016 12:11:36 PM] Initializing the Game resources
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniform1dEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniform2dEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniform3dEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniform4dEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniform1dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniform2dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniform3dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniform4dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix2dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix3dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix4dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix2x3dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix2x4dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix3x2dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix3x4dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix4x2dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glProgramUniformMatrix4x3dvEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glVertexArrayVertexAttribDivisorEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glTextureStorage1DEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glTextureStorage2DEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glTextureStorage3DEXT
[WARNING 01/03/2016 12:11:36 PM] [LWJGL] Failed to locate address for GL function glVertexArrayVertexAttribLOffsetEXT
[TRACE 01/03/2016 12:11:36 PM]
com.shc.silenceengine.core.SilenceException: java.lang.NullPointerException
	at com.shc.silenceengine.utils.FileUtils.readToByteBuffer(FileUtils.java:159)
	at com.shc.silenceengine.backend.lwjgl3.opengl.Texture.fromInputStream(Texture.java:144)
	at com.shc.silenceengine.backend.lwjgl3.opengl.Texture.fromFilePath(Texture.java:127)
	at com.shc.silenceengine.core.ResourceLoader.textureLoadHelper(ResourceLoader.java:100)
	at com.shc.silenceengine.core.ResourceLoader.asyncLoadResources(ResourceLoader.java:284)
	at java.lang.Thread.run(Thread.java:745)

	at com.shc.silenceengine.core.SilenceException.reThrow(SilenceException.java:73)
	at com.shc.silenceengine.utils.FileUtils.readToByteBuffer(FileUtils.java:171)
	at com.shc.silenceengine.backend.lwjgl3.opengl.Texture.fromInputStream(Texture.java:144)
	at com.shc.silenceengine.backend.lwjgl3.opengl.Texture.fromFilePath(Texture.java:127)
	at com.shc.silenceengine.core.ResourceLoader.textureLoadHelper(ResourceLoader.java:100)
	at com.shc.silenceengine.core.ResourceLoader.asyncLoadResources(ResourceLoader.java:284)
	at java.lang.Thread.run(Thread.java:745)

AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code 255
```

Ps
I found another problem in __ResourceFilePath::getJarEntries__ with this line:

```
String jarPath = URLDecoder.decode(jarUrl.substring(jarUrl.indexOf('/') + 1, jarUrl.indexOf('!')), "UTF-8");
```
causing this error:

```
java.io.FileNotFoundException: Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/ant-javafx.jar (No such file or directory)
```

On mac the fix consist of simply deleting the _+1_ so we don't skip the first '/'. I couldn't find unit test around these feature. Anyways, it becomes:

```
String jarPath = URLDecoder.decode(jarUrl.substring(jarUrl.indexOf('/'), jarUrl.indexOf('!')), "UTF-8");
```

I'll make a PR as soon as I find the time.

**Comment by fagossa** [comment]
I found that the error comes from __Texture::fromFilePath(FilePath)__ because the _path_ specified could not be found.

However, this seems odd as the file do exist in my resources directory: _resources/space_ship_gold.png_.

As the problem could come from different sources (relative path, my own gradle, jdk bug, etc) I will investigate on the subject and update the issue accordingly.

**Comment by sriharshachilakapati** [comment]
The texture problem is a separate problem, so please kindly make a new issue for that. I'd like to see what is this statement printing for you:

```java
System.out.println(ResourceFilePath.class.getClassLoader().getResource(filePath.getPath()));
```

Test that with the file path which is having issue. As far as I can tell, there is something which is trying to fetch from `ant-javafx.jar` which should not be the case, SilenceEngine does not rely on JavaFX.

**Comment by fagossa** [comment]
I migrated from _jdk8_0_25_ to _jdk8_0_66_ because the previous error was related to an _ant-javafx.jar_ not found.

I printed what you suggested and also the absolute path, like this:
```
System.out.println(ResourceFilePath.class.getClassLoader().getResource(filePath.getPath()));
System.out.println(filePath.getAbsolutePath());
```

And as long as the searched resource comes from engine's resources directory I get this:

```
file:/Users/myUser/Documents/myprojects/SEtest/SilenceEngine/build/resources/main/resources/logo_dark.png
resources/logo_dark.png
```

However, when the resources come from my own resources folder (_src/main/resources_) then I get:
```
null
resources/space_ship_mother.png
```

Just in case my folder tree is as follows
```
|SEtest
|- AutoInvaders
|-- src
|---- main
|------ java
|------ resources
|
|- SilenceEngine
|-- src
|---- main
|------ java
|-------- resources
```

**Comment by sriharshachilakapati** [comment]
Okay the issue is in the setup, the files in `src\main\resources\` in your application will usually go into the root of the JAR, unless configured in the Gradle build script manually. Try calling for your image with just the file name.

```java
FilePath.getResourceFile("space_ship_mother.png").exists(); // Should be true
```

**Comment by fagossa** [comment]
you're right!!

instead of specifying the _resource_ directory like this:

```
FilePath.getResourceFile("resource/space_ship_mother.png")
```

I just need to 

```
FilePath.getResourceFile("space_ship_mother.png")
```
