### ISSUE TITLE
AMD shouts on Pre GL3 shaders in Core profile

### ISSUE THREAD

**Issue by sriharshachilakapati** [sriharshachilakapati/SilenceEngine#74]
AMD doesn't seem to like shaders of version 110 in Core 3.3 OpenGL contexts. Received a exception as follows:

~~~
Exception in thread "main" com.shc.silenceengine.graphics.opengl.GLException: Unable to compile shader:
Vertex shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated


        at com.shc.silenceengine.graphics.opengl.Shader.compile(Shader.java:91)
        at com.shc.silenceengine.graphics.programs.FontProgram.lambda$1(FontProgram.java:56)
        at com.shc.silenceengine.backend.lwjgl.LwjglFileReader.lambda$3(LwjglFileReader.java:100)
        at com.shc.silenceengine.utils.TaskManager.forceUpdateTasks(TaskManager.java:61)
        at com.shc.silenceengine.core.EventManager.raiseUpdateEvent(EventManager.java:172)
        at com.shc.silenceengine.core.gameloops.FixedTimeSteppedLoop.performLoopFrame(FixedTimeSteppedLoop.java:75)
        at com.shc.silenceengine.backend.lwjgl.LwjglRuntime.start(LwjglRuntime.java:96)
        at com.shc.silenceengine.tests.lwjgl.ControllerTestRun.main(ControllerTestRun.java:38)
AL lib: (EE) alc_cleanup: 1 device not closed
~~~

It means we need a new shader for Core Profile OpenGL and also maintain old shaders for WebGL and OpenGL ES. Maybe it is time to start working on a shader system.

**Comment by sriharshachilakapati** [comment]
This is now fixed as the shaders are now transformed before compilation to GL3 shaders on desktop and GLSL 100 on HTML5 and Android.
