### ISSUE TITLE
Issue with parsing APK

### ISSUE THREAD

**Issue by darkhax** [sriharshachilakapati/SilenceEngine#76]
I am currently trying to run a unit test of sorts on android using the Silence Engine, however I get a parsing error when I try to install the app. This happens with all 3 generated APK files. Could you test and see if it's an issue with the apk? [download](https://www.dropbox.com/s/bkplmtoehdzls04/SilenceCommonsAndroid-release-unsigned.apk?dl=0)

As for what the app actually does, it runs 12 tests on the device, which time how long Oracle's Random takes to generate large amounts of various things, and then compares it against my implementation of Random, and a friends alternative version. This test is pretty taxing on the CPU, so I wouldn't recommend running it past a few seconds. 

Edit: The specs of my device should be able to hit Silence Engine's minimum. It's an Asus Zenfone 2 ZE551ML running Android 5.0.

**Comment by sriharshachilakapati** [comment]
Installing this package gives me this on the terminal through ADB.

~~~
adb install SilenceCommonsAndroid-release-unsigned.apk
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
284 KB/s (1255765 bytes in 4.312s)
        pkg: /data/local/tmp/SilenceCommonsAndroid-release-unsigned.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
~~~

This is because unsigned APKs cannot be installed on a real device. SilenceEngine apps cannot run in an emulator because of the requirement of OpenGL ES 3.0, and hence your APK cannot be installed and run.

You want to [self sign your apk](https://developer.android.com/studio/publish/app-signing.html#signing-manually) in order for it to get installed on a device. If it is for your own testing, use debug builds, or better use desktop backend while development and test it on android after everything is working.

**Comment by darkhax** [comment]
Thank you for pointing out all of the earlier issues. After correcting them, I am still having the parse issue however. Using adb I get the following response.

```
C:\adb>adb install xor.apk
7309 KB/s (1286401 bytes in 0.171s)
        pkg: /data/local/tmp/xor.apk
Failure [INSTALL_FAILED_OLDER_SDK]
```
Not sure if this is related to the device or the PC. The new download is [here](https://www.dropbox.com/s/jmsvtgym9vz72qi/xor.apk?dl=0). As for testing, this application was created for the sole purpose of testing the performance of certain code on physical devices, so the desktop edition is not accurate enough.

**Comment by sriharshachilakapati** [comment]
Dunno, but it installed fine, but it failed to run. 

~~~
C:\Users\Harsha\Downloads> adb install xor.apk
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
289 KB/s (1286401 bytes in 4.342s)
        pkg: /data/local/tmp/xor.apk
Success
~~~

**Comment by sriharshachilakapati** [comment]
I have got some logcat output for you, and it seems that you are calling `SilenceEngine` methods before they are initialized.

~~~
E AndroidRuntime: FATAL EXCEPTION: GLThread 1723
E AndroidRuntime: Process: xyz.epoxide.silencecommons.android, PID: 2062
E AndroidRuntime: java.lang.ExceptionInInitializerError
E AndroidRuntime:        at xyz.epoxide.silencecommons.android.SilenceCommonsLauncher.launchGame(SilenceCommonsLauncher.java:15)
E AndroidRuntime:        at com.shc.silenceengine.backend.android.AndroidLauncher$$Lambda$1.invoke(Unknown Source)
E AndroidRuntime:        at com.shc.silenceengine.backend.android.AndroidWindow.onSurfaceCreated(AndroidWindow.java:51)
E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.shc.silenceengine.logging.Logger com.shc.silenceengine.logging.ILogDevice.getLogger(java.lang.String)' on a null object reference
E AndroidRuntime:        at xyz.epoxide.silencecommons.SilenceCommons.<clinit>(SilenceCommons.java:23)
E AndroidRuntime:        ... 5 more
E AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
~~~

The device objects in the `SilenceEngine` class will be null until you call the runtime, and it is that you are using the logger before the engine is initialized, that is in the `launchGame` method. This is why your app is failing to launch.

**Comment by darkhax** [comment]
After digging into things a bit further, I think I have found the source of the issue. By default Silence Engine sets the minimum SDK to 22, however Android 5.0 is SDK 21. I went threw the gradle script to manually lower the minimum SDK (Since 5.0 was listed as the lowest android version required) however I got the following issue. 

```
```

**Comment by sriharshachilakapati** [comment]
Will fix that by tonight. The same thing also happens with AndroidOpenAL project which is a dependency of android backend. Will change every thing by tonight.

**Comment by darkhax** [comment]
Okay, thank you for looking into this. I will hold off on updating to 6.0 until then, so we can confirm that the issue has been solved.

**Comment by sriharshachilakapati** [comment]
I have reduced the minimum Android SDK to 21 (Lollipop). Can you try it now again?

**Comment by darkhax** [comment]
After re-downloading the project creator and making a new project, the sdk version was set to 22 by default. After changing it, I got the same error as before. 

```
* What went wrong:
Execution failed for task ':CommonsAndroid:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 22 declared in library [:backend-android-debug:] C:\Users\darkh\Desktop\commons\CommonsAndroid\build\intermediates\exploded-aar\backend-android-debug\AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.shc.silenceengine.backend.android" to force usage

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':CommonsAndroid:processDebugManifest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:241)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:214)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:207)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 22 declared in library [:backend-android-debug:] C:\Users\darkh\Desktop\commons\CommonsAndroid\build\intermediates\exploded-aar\backend-android-debug\AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.shc.silenceengine.backend.android" to force usage
        at com.android.builder.core.AndroidBuilder.mergeManifests(AndroidBuilder.java:686)
        at com.android.build.gradle.tasks.MergeManifests.doFullTaskAction(MergeManifests.java:65)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:82)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
```

**Comment by sriharshachilakapati** [comment]
I haven't yet updated the binaries in the project creator, in the sense that the project is not a released version. Please compile it yourselves and replace the library files.

**Comment by darkhax** [comment]
I can't compile it myself if you do not push the code to GitHub.

**Comment by sriharshachilakapati** [comment]
Did you get this working? In that case, this can be closed.

**Comment by darkhax** [comment]
Yes, this change fixed my issues. Was able to run the test apps from silence fine.
